// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_suW__e_lPkh9nASoHv8Ol1IsI4DECu4',
    appId: '1:461113159656:android:f9486aca23fb5dfd237e5d',
    messagingSenderId: '461113159656',
    projectId: 'my-bu-b1526',
    storageBucket: 'my-bu-b1526.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXfTz3eKqdPxshyUCEO_KTeZZPU-WAQ0s',
    appId: '1:461113159656:ios:73f40845897b2f94237e5d',
    messagingSenderId: '461113159656',
    projectId: 'my-bu-b1526',
    storageBucket: 'my-bu-b1526.appspot.com',
    androidClientId: '461113159656-fjbo6lcuo412id1j98bcl37dkkagueib.apps.googleusercontent.com',
    iosClientId: '461113159656-4metf01ii7ubh5vtp63rqr748p541bja.apps.googleusercontent.com',
    iosBundleId: 'software.ecz.mybu',
  );
}
